"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var mago_1 = require("./mago");
var luchador_1 = require("./luchador");
var arquero_1 = require("./arquero");
var hechicero_1 = require("./hechicero");
var guerrero_1 = require("./guerrero");
var mago = new mago_1.Mago("Houdini");
var luchador = new luchador_1.Luchador("Dwayne The rock Johnson");
var arquero = new arquero_1.Arquero("Robin Hood");
var hechicero = new hechicero_1.Hechicero("Satoru Gojo");
var guerrero = new guerrero_1.Guerrero("Radnar Lodbrok");
console.log(mago.toString());
console.log(luchador.toString());
console.log(arquero.toString());
console.log(hechicero.toString());
console.log(guerrero.toString());
mago.atacar();
luchador.atacar();
arquero.atacar();
hechicero.atacar();
guerrero.atacar();
